spring.application.name=BookDownload

spring.datasource.url=jdbc:postgresql://db.xmhvqgtzsrskuckarzrp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

logging.level.com.jiang.dao=debug

# ===== Cloudinary 配置（新增）=====
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# =====跨域配置=====
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allow-credentials=true

server.port=${PORT:8080}